# Generated by Django 2.2.5 on 2019-09-08 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('introduction', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=512)),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
